# This scenario is templated with Jinja2 and rendered for each group (see sample sheet).
# A variable `samples` is available, holding the dataframe of
# the sample sheet, filtered to those samples contained in the group to be rendered.
# For example, this can be used to pass arbitrary column values (like the purity below),
# to the sample definitions.
# Note that sample names here must correspond to the alias column in the sample sheet.

samples:
  index:
    resolution: 5
    universe: "0.0 | 0.5 | 1.0"
  father:
    resolution: 5
    universe: "[0.0,0.15] | 0.5 | 1.0"
  mother:
    resolution: 5
    universe: "[0.0,0.15] | 0.5 | 1.0"

events:
  denovo: "index:[0.5,1.0] & father:0.0 & mother:0.0"
  homozygous_recessive: "index:1.0 & mother:0.5 & father:0.5"
  compound_heterozygous_candidate_mother: "index:0.5 & father:0.0 & mother:0.5"
  compound_heterozygous_candidate_father: "index:0.5 & father:0.5 & mother:0.0"
  not_interesting: "index:0.0 | father:1.0 | mother:1.0 | (index:0.5 & mother:0.5 & father:0.5)"
